### ISSUE TITLE
`#!/usr/bin/env -S node --import tsx/esm` cause a parse error

### ISSUE THREAD

**Issue by mizdra** [privatenumber/tsx#358]
### Problem

Combining `shebang` with `node --import tsx/esm` causes a parsing error.

```ts
#!/usr/bin/env -S node --import tsx/esm

console.log('hello');
```

```
$ ./scripts/hello.ts

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: Parse error @:2:20
    at Oe (file:///Users/mizdra/src/github.com/mizdra/reproduction-tsx-parsing-error/node_modules/tsx/dist/index-9eae64fa.mjs:8:8007)
    at BA (file:///Users/mizdra/src/github.com/mizdra/reproduction-tsx-parsing-error/node_modules/tsx/dist/index-9eae64fa.mjs:13:66)
    at Ie (file:///Users/mizdra/src/github.com/mizdra/reproduction-tsx-parsing-error/node_modules/tsx/dist/index-9eae64fa.mjs:21:85)
    at or (file:///Users/mizdra/src/github.com/mizdra/reproduction-tsx-parsing-error/node_modules/tsx/dist/index-9eae64fa.mjs:22:1132)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Qr (file:///Users/mizdra/src/github.com/mizdra/reproduction-tsx-parsing-error/node_modules/tsx/dist/index-9eae64fa.mjs:22:2155)
    at async Z (file:///Users/mizdra/src/github.com/mizdra/reproduction-tsx-parsing-error/node_modules/tsx/dist/esm/index.mjs:13:1786)
    at async nextLoad (node:internal/modules/esm/hooks:833:22)
    at async Hooks.load (node:internal/modules/esm/hooks:416:20)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:168:18) {
  idx: 59
}

Node.js v20.8.1
```

### Expected behavior

No error occurred.

### Minimal reproduction URL

https://github.com/mizdra/reproduction-tsx-parsing-error

### Version

3.14.0

### Node.js version

20.8.1

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by mizdra** [comment]
The workaround I have found for this problem is to use the `tsx` command.

```ts
#!/usr/bin/env -S npx tsx

console.log('hello');
```

```console
$ ./scripts/hello-without-node-command.ts
hello
```

However, I want to use `tsx` via the `node` command in order to use `node --env-file`. Therefore, I cannot use the workaround.

**Comment by eugene1g** [comment]
`#!/usr/bin/env -S node --import=tsx/esm` Works

**Comment by privatenumber** [comment]
@eugene1g
Confirming your solution works. Thanks

@mizdra 
tsx accepts all Node.js flags: `tsx --help`
That means you can do `tsx --env-file`

**Comment by mizdra** [comment]
Thanks! I'll try it.

**Comment by mizdra** [comment]
https://github.com/privatenumber/tsx/issues/358#issuecomment-1792634859 solved my problem. Thank you very much!
