### ISSUE TITLE
"___tsxInteropDynamicImport is not defined" since 4.0.0

### ISSUE THREAD

**Issue by jmerle** [privatenumber/tsx#382]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

See https://github.com/jmerle/tsx-puppeteer-example for a minimal example of a project using tsx and [Puppeteer](https://github.com/puppeteer/puppeteer). With tsx 3.14.0, running `pnpm start` shows an empty Chrome tab for 5 seconds and then exits. With tsx 4.0.0 or 4.1.0, without changing the code or the version of any of the other dependencies, the browser does not open and the following error is shown in the console instead:
```
$ pnpm start

> tsx-puppeteer-example@0.0.0 start /home/jasper/Projects/tsx-puppeteer-example
> tsx index.ts

/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Debug.js:26
        debugModule = (await import('debug')).default;
^


ReferenceError: ___tsxInteropDynamicImport is not defined
    at importDebug (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Debug.js:26:1)
    at debugLevel (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Debug.js:74:1)
    at <anonymous> (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/src/cdp/Connection.ts:135:7)
    at CallbackRegistry.create (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:40:7)
    at Connection._rawSend (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/src/cdp/Connection.ts:128:22)
    at Connection.send (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/src/cdp/Connection.ts:116:17)
    at ChromeTargetManager.initialize (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/src/cdp/ChromeTargetManager.ts:146:28)
    at CdpBrowser._attach (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/src/cdp/Browser.ts:164:31)
    at Function._create (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/src/cdp/Browser.ts:80:19)
    at ChromeLauncher.launch (/home/jasper/Projects/tsx-puppeteer-example/node_modules/.pnpm/puppeteer-core@21.5.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:116:1)

Node.js v20.9.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

I expect tsx 4.0.0 to be able to run the same code tsx 3.14.0 was able to run.

### Minimal reproduction URL

https://github.com/jmerle/tsx-puppeteer-example

### Version

v4.0.0

### Node.js version

v20.9.0

### Package manager

pnpm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for your issue and reproduction! Very helpful
