### ISSUE TITLE
Transforming JavaScript decorators to the configured target environment ("nodeXX.Y.Z") is not supported yet

### ISSUE THREAD

**Issue by darcyrush** [privatenumber/tsx#393]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

Even when a `tsconfig.json` containing `"experimentalDecorators": true` is in the `root` folder as the `package.json`, when running the commands using `tsx` or `node` importing `tsx` the following error is output

```
> npx tsx --tsconfig ./src/tsconfig.json src/main.ts

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

Error: Transform failed with 2 errors:
/home/drush/Workspace/pocs/tsx-min-repo/src/health.controller.ts:3:0: ERROR: Transforming JavaScript decorators to the configured target environment ("node21.2.0") is not supported yet
/home/drush/Workspace/pocs/tsx-min-repo/src/health.controller.ts:5:2: ERROR: Transforming JavaScript decorators to the configured target environment ("node21.2.0") is not supported yet
    at failureErrorWithLog (/home/drush/Workspace/pocs/tsx-min-repo/node_modules/esbuild/lib/main.js:1649:15)
    at /home/drush/Workspace/pocs/tsx-min-repo/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/home/drush/Workspace/pocs/tsx-min-repo/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/home/drush/Workspace/pocs/tsx-min-repo/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/home/drush/Workspace/pocs/tsx-min-repo/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 0,
        file: '/home/drush/Workspace/pocs/tsx-min-repo/src/health.controller.ts',
        length: 1,
        line: 3,
        lineText: '@Controller()',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Transforming JavaScript decorators to the configured target environment ("node21.2.0") is not supported yet'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 2,
        file: '/home/drush/Workspace/pocs/tsx-min-repo/src/health.controller.ts',
        length: 1,
        line: 5,
        lineText: "  @Get('health/readiness')",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Transforming JavaScript decorators to the configured target environment ("node21.2.0") is not supported yet'
    }
  ],
  warnings: []
}
```  

### Expected behavior

I expect tsx should discover and use the  `"experimentalDecorators": true` value within `tsconfig.json` using either `--tsconfig <path>` or the `TSX_TSCONFIG_PATH` env variable.

### Minimal reproduction URL

https://github.com/darcyrush/tsx-min-repo

### Version

4.1.2

### Node.js version

21.2.0

### Package manager

npm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Sounds like an esbuild limitation. Can you also file it over at https://github.com/evanw/esbuild?

**Comment by privatenumber** [comment]
This is happening because of tsx's implementation of tsconfig. You only listed `main.ts` in `tsconfig.json#files` so it only applies that config to `main.ts`.

Seems TypeScript compiler constructs a dependency tree from `files` and applies the tsconfig to all of them. I can fix tsx to follow this behavior, but it would really throw a wrench into scenarios where users want to load multiple tsconfigs (monorepos).

For now, you can work around this by adjusting your `files` or `includes` in `tsconfig.json`.

**Comment by darcyrush** [comment]
> Seems TypeScript compiler constructs a dependency tree from files and applies the tsconfig to all of them.

Yes, I stumbled across this 'feature' and find that it works well with `es-lint` as super cheap tree-shaking to find unused files in our projects. It would be great if `tsx` could emulate the same behavior as `tsc` in this respect at some point in the future.

> it would really throw a wrench into scenarios where users want to load multiple tsconfigs (monorepos).

This is an interesting comment, as for a concurrent project I am investigating using a monorepo in combination with `npm` workspaces and would love to use `tsx` in both cases using `files` and the `tsc` dependency tree logic.

> I can fix tsx to follow this behavior

If you eventually have a working branch or rc release that manages to allow the use of monorepos alongside the `tsc` dependency tree logic, I am happy to test with both a normal and monorepo.

For now I confirm that `include` with all files works around this issue. Thank you for investigating.

**Comment by odinho** [comment]
We just upgraded from version 3 to 4 to get support for new keyword `using`.

```diff
-    "tsx": "^3.12.7",
+    "tsx": "^4.7.0",
```

We then started hitting this issue.  We have some scripts that use `tsx` in their own folder, and we now have to list all files in the other project i.e. many lines of `../apps/web/src/core/MyThingWithDecorator1.ts` in each `tsconfig.json` file that isn't the main one in `apps/web/`. That will quickly become quite a maintenance burden, but it's what we decided to do right now.

Did something change from 3 to 4 to make this no longer work? Why would it work on on `3.12.7` but not on `4.7.0`?

**Comment by RobertAKARobin** [comment]
@privatenumber I turned `experimentalDecorators` off in order to use [the new standard of decorators](https://github.com/microsoft/TypeScript/pull/50820), and this causes the "Transforming JavaScript decorators..." error to occur again.

**Comment by privatenumber** [comment]
This thread is being locked now that the bug is confirmed, and the recent conversation hasn't been productive in finding a solution.

Issues is intended for reporting and fixing bugs rather than seeking one-off workarounds & help. However, if you're looking for a workaround, please read the previous conversation.
