### ISSUE TITLE
dynamic import breaks line numbers in stack traces

### ISSUE THREAD

**Issue by neelance** [privatenumber/tsx#404]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

This code reports a stack trace with broken line numbers:
```ts
async function main(): Promise<void> {
  console.log(1);
  console.log(2);
  console.log(3);

  throw new Error("HERE");

  await import("some-import-statment");
}

main().catch(console.error);
```
The broken stack trace:
```
Error: HERE
    at main (.../index.ts:1:188)
    at <anonymous> (.../index.ts:9:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```

### Expected behavior

With the `import` line commented out the stack trace is correct:
```
Error: HERE
    at main (.../index.ts:6:9)
    at <anonymous> (.../index.ts:11:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```

### Minimal reproduction URL

See above.

### Version

v4.2.0

### Node.js version

v20.9.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [X] I plan to make a financial contribution to this project (sponsoring via @afilio-de)

**Comment by privatenumber** [comment]
Thank you for the issue and sponsorship! Fix will be released shortly

**Comment by neelance** [comment]
Thanks for fixing!

It seems like there is still some bad information in my tsx cache. How can I clear it?

**Comment by privatenumber** [comment]
Oops I shoudlve handled this in the cache key. Will fix that shortly.

**Comment by privatenumber** [comment]
Try https://github.com/privatenumber/tsx/releases/tag/v4.3.0

**Comment by neelance** [comment]
Works! 👍
