### ISSUE TITLE
"[DEP0040] The punycode module is deprecated" with Node.js 21.x

### ISSUE THREAD

**Issue by AnYiEE** [privatenumber/tsx#432]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://github.com/yarnpkg/yarn/issues/9005

### Version

v4.6.2

### Node.js version

v21.3.0

### Package manager

pnpm

### Operating system

Windows

### Problem & Expected behavior

Please refer to https://github.com/yarnpkg/yarn/issues/9005, is the same as situation.

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by AnYiEE** [comment]
This is an error message. It seems to be a problem with the psl package, sorry for any inconvenience caused.

```
(node:10880) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:401:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (node_modules\.pnpm\psl@1.9.0\node_modules\psl\index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.S (node_modules\.pnpm\tsx@4.6.2\node_modules\tsx\dist\cjs\index.cjs:1:1292)
```
