### ISSUE TITLE
Unexpected `top-level await error` for `type: module` + top level await in `node_modules`

### ISSUE THREAD

**Issue by JounQin** [privatenumber/tsx#552]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/JounQin/test/tree/tsx

### Version

4.10.1

### Node.js version

v20.11.0

### Package manager

yarn

### Operating system

macOS

### Problem & expected behavior (under 200 words)

```ts
// test.ts
import prettier from 'prettier'

const main = async () => {
  await prettier.resolveConfig('README.md')
}

main()
```

`prettier@v3` is a dual package, I have `type: module` in my `package.json`, it should be run in ESM module, and it will resolve its own configs with `import()`, `@1stg/prettier-config` is a pure ESM package with [top level await used](https://github.com/1stG/configs/blob/1a6ee0201a8da04ffe917554a662407b9901d799/packages/prettier-config/base.js#L20), it should just work without runtime exception

<details>
<summary>But it just throws like the following:</summary>

```log
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Transform failed with 1 error:
/Users/JounQin/Workspaces/GitHub/test/node_modules/@1stg/prettier-config/base.js:20:11: ERROR: Top-level await is currently not supported with the "cjs" output format
    at failureErrorWithLog (/Users/JounQin/Workspaces/GitHub/test/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/JounQin/Workspaces/GitHub/test/node_modules/esbuild/lib/main.js:849:29
    at responseCallbacks.<computed> (/Users/JounQin/Workspaces/GitHub/test/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/Users/JounQin/Workspaces/GitHub/test/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/Users/JounQin/Workspaces/GitHub/test/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  name: 'TransformError'
}

Node.js v20.11.0
```
</details>

I'm not for sure why `node_modules` packages are also transformed by `esbuild`, is that expected to be transformed or configurable?

### Contributions

- [ ] I'm interested in working on this issue
- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Thanks for the bug report @JounQin 

tsx supports loading ESM in Node's _CommonJS mode_ by compiling it to CommonJS syntax... so if a module file (.mjs or `package.json#type: 'module'`) gets `require()`'d, it gets converted to CommonJS. Since `require()` is sync, it cannot handle top-level await. Basically, this is the same limitation as the recent improvement in Node: https://github.com/nodejs/node/pull/51977

Looking at Prettier's code, it looks like it tries `require()` first, and if it fails, it tries `import()`. Because we want it to go to `import()` (which supports TLA), you can opt-in only to the ESM enhancement:
```sh
node --import tsx/esm scripts/test
```

This way, the `require()` will fail, and skip to the import() and the TLA file will get loaded expectedly.

**Comment by eric-burel** [comment]
For googlers hitting this error when running a top leval await, eg in a script calling an API: adding `"type": "module"` in your package.json should fix this error.

**Comment by privatenumber** [comment]
Fixed in [tsx v4.23.11](https://github.com/privatenumber/tsx/releases/tag/v4.23.11).

tsx now attaches Node's expected `ERR_REQUIRE_ESM` or `ERR_REQUIRE_ASYNC_MODULE` code when `require()` cannot synchronously load ESM containing top-level await. Callers such as Prettier can catch that code and fall back to `import()`, allowing the asynchronous ESM config to load normally while preserving the original transform diagnostic.
