### ISSUE TITLE
Apply rootDir/outDir when resolving imports

### ISSUE THREAD

**Issue by JavaScriptBach** [privatenumber/tsx#603]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/JavaScriptBach/ts-repo-structure

### Problem & expected behavior (under 200 words)

# The Problem
I have a Typescript monorepo with source files in `<package>/src/*.ts` and js files outputted to `<package>/dist/*.js`. Each package also uses `imports` and `exports` in the package.json to control entry points and allow for bare imports. A small repro is linked below.

This configuration works perfectly in Typescript and Node, but not in `tsx`.
- Typescript's language server in VSCode is able to evaluate these imports, highlight suggestions, link correctly to references etc even before anything is compiled
- Typescript is able to compile the code
- Node.js is able to run the compiled code
- However, `tsx` is NOT able to run this code before it's compiled.

I think the key missing section is [here](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-imports-and-self-name-imports). It looks like we did some extension remapping in https://github.com/privatenumber/tsx/issues/59, but I think we also need handle `rootDir` and `outDir` to have full parity with Typescript.

> If the package.json is part of the local project, an additional remapping step is performed in order to find the input TypeScript implementation file that will eventually produce the output JavaScript or declaration file path that was resolved from "imports". Without this step, any compilation that resolves an "imports" path would be referencing output files from the previous compilation instead of other input files that are intended to be included in the current compilation. This remapping uses the outDir/declarationDir and rootDir from the tsconfig.json, so using "imports" usually requires an explicit rootDir to be set.

# Repro

1. Check out https://github.com/JavaScriptBach/ts-repo-structure and run `yarn`
2. Run `npx tsx a/src/a.ts`

```
node:internal/modules/cjs/loader:1068
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module '/Users/philliphuang/ts-repo-structure/node_modules/b/dist/a.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1068:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1061:15)
    at resolveExports (node:internal/modules/cjs/loader:538:14)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1033:27)
    at resolve (/Users/philliphuang/ts-repo-structure/node_modules/tsx/dist/register-BujtrvNV.cjs:1:3084)
    at resolveRequest (/Users/philliphuang/ts-repo-structure/node_modules/tsx/dist/register-BujtrvNV.cjs:1:2618)
    at Function._resolveFilename (/Users/philliphuang/ts-repo-structure/node_modules/tsx/dist/register-BujtrvNV.cjs:1:3400)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/philliphuang/ts-repo-structure/node_modules/b/package.json'
}
```

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by Pagebakers** [comment]
Can confirm this is an issue in our monorepo with yarn (node_modules linker) as well.

**Comment by privatenumber** [comment]
When I run `tsc --noEmit` in your repro, TypeScript emits these errors:
```
a/src/a.ts:2:17 - error TS2307: Cannot find module 'b/a' or its corresponding type declarations.

2 import foo from "b/a";
                  ~~~~~

a/src/a.ts:3:17 - error TS2307: Cannot find module 'b/c' or its corresponding type declarations.

3 import bar from "b/c";
                  ~~~~~

a/src/a.ts:5:29 - error TS2307: Cannot find module 'a/b' or its corresponding type declarations.

5 import myLocalFunction from "a/b";
                              ~~~~~

a/src/a.ts:6:55 - error TS2307: Cannot find module '#a/c' or its corresponding type declarations.

6 import { myPrivateFunction, myPrivateFunction2 } from "#a/c";
                                                        ~~~~~~


Found 4 errors in the same file, starting at: a/src/a.ts:2
```

With `--traceResolution`:
```
======== Resolving module 'b/a' from '~/Desktop/ts-repo-structure/a/src/a.ts'. ========
Module resolution kind is not specified, using 'Node16'.
Resolving in CJS mode with conditions 'require', 'types', 'node'.
File '~/Desktop/ts-repo-structure/a/src/package.json' does not exist according to earlier cached lookups.
File '~/Desktop/ts-repo-structure/a/package.json' exists according to earlier cached lookups.
Loading module 'b/a' from 'node_modules' folder, target file types: TypeScript, JavaScript, Declaration, JSON.
Searching all ancestor node_modules directories for preferred extensions: TypeScript, Declaration.
Directory '~/Desktop/ts-repo-structure/a/src/node_modules' does not exist, skipping all lookups in it.
Directory '~/Desktop/ts-repo-structure/a/node_modules' does not exist, skipping all lookups in it.
Found 'package.json' at '~/Desktop/ts-repo-structure/node_modules/b/package.json'.
Using 'exports' subpath './*' with target './dist/a.js'.
File name '~/Desktop/ts-repo-structure/node_modules/b/dist/a.js' has a '.js' extension - stripping it.
Export specifier './a' does not exist in package.json scope at path '~/Desktop/ts-repo-structure/node_modules/b'.
Directory '~/Desktop/ts-repo-structure/node_modules/@types' does not exist, skipping all lookups in it.
Directory '~/Desktop/node_modules' does not exist, skipping all lookups in it.
Directory '~/node_modules' does not exist, skipping all lookups in it.
Directory '/Users/node_modules' does not exist, skipping all lookups in it.
Directory '/node_modules' does not exist, skipping all lookups in it.
Searching all ancestor node_modules directories for fallback extensions: JavaScript, JSON.
Directory '~/Desktop/ts-repo-structure/a/src/node_modules' does not exist, skipping all lookups in it.
Directory '~/Desktop/ts-repo-structure/a/node_modules' does not exist, skipping all lookups in it.
File '~/Desktop/ts-repo-structure/node_modules/b/package.json' exists according to earlier cached lookups.
Using 'exports' subpath './*' with target './dist/a.js'.
File name '~/Desktop/ts-repo-structure/node_modules/b/dist/a.js' has a '.js' extension - stripping it.
Export specifier './a' does not exist in package.json scope at path '~/Desktop/ts-repo-structure/node_modules/b'.
Directory '~/Desktop/node_modules' does not exist, skipping all lookups in it.
Directory '~/node_modules' does not exist, skipping all lookups in it.
Directory '/Users/node_modules' does not exist, skipping all lookups in it.
Directory '/node_modules' does not exist, skipping all lookups in it.
======== Module name 'b/a' was not resolved. ========
```

Am I missing something?

**Comment by gaastonsr** [comment]
If I understand the repro correctly, it doesn't make sense to compile the files at the root level, since it's a monorepo and each workspace inside should be compiled independently since they are independent projects in the same repo.

In this case before you compile (or type check) the files in the workspace `a` you need to compile first the workspace `b` because the `tsconfig.json` of `a` says that it should only include `src/**/*.ts` in the compilation and it should treat `b` as an external dependency.

Leaving aside the compilation process, it's important to note that when [`#a/c` is imported](https://github.com/JavaScriptBach/ts-repo-structure/blob/a91cbc39ed9ead17b3d1d5119e7c8485b2d608bd/a/src/a.ts#L6) Typescript can locate the file without issues even though in the `package.json` file [it's pointing to the `dist` file](https://github.com/JavaScriptBach/ts-repo-structure/blob/a91cbc39ed9ead17b3d1d5119e7c8485b2d608bd/a/package.json#L13).

**Comment by JavaScriptBach** [comment]
Yes, what @gaastonsr said is correct. In this example `a` is a workspace that depends on `b`.  It is set up using [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) so when `a` is compiled using `tsc -b`, the workspaces will get built in the right order.

If you open this project in an IDE (e.g. VSCode with the Typescript extension), all the language servers work and the resulting compiled code also runs in Node.js. The ask here is that `tsx` also learns how to run code written with this setup as well.

**Comment by tao-cumplido** [comment]
I came up with a workaround, maybe it's useful to someone else:
I run tsx with a custom condition, e.g. `tsx --conditions tsx` and an `imports` field like this in `package.json`:
```json
{
  "#*.js": {
    "tsx": "./src/*.js",
    "default": "./dist/*.js"
  }
}
```

**Comment by privatenumber** [comment]
Closing as duplicate of #714. #714 has the more focused reproduction for TypeScript rootDir/outDir remapping of subpath imports, so track the resolver behavior there.
